机器配置

node1:192.168.186.163

在node1上配置ssh
$ sudo ssh-keygen
$ sudo ssh-copy-id -i /root/.ssh/id_rsa.pub root@192.168.186.163
测试ssh
$ sudo ssh root@192.168.186.163
均可免密登陆

在node1上安装kubespray环境
$ sudo yum -y install epel-release
$ sudo yum clean all && sudo yum makecache
$ sudo yum install -y python-pip python34 python-netaddr python34-pip ansible git
$ git clone https://github.com/kubernetes-sigs/kubespray
$ cd kubespray
$ sudo pip install -r requirements.txt

生成inventory文件
$ cp -rfp inventory/sample inventory/testcluster
$ cp -rfp inventory/local/hosts.ini inventory/testcluster/
下载所需资源
$ ansible-playbook -i inventory/testcluster/hosts.ini cluster.yml -t download -b -v -k
FAILED! => {"attempts": 4, "changed": false, "cmd": "/usr/bin/docker pull gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.3.0", "msg": "[Errno 2] No such file or directory", "rc": 2}
搭建私库，修改roles/download/defaults/main.yml文件，从私库下载镜像
类似的需要从私库拉镜像的还有
pause
etcd
kubernetes-dashboard
再试
$ ansible-playbook -i inventory/testcluster/hosts.ini cluster.yml -t download -b -v -k
FAILED! => {"attempts": 4, "changed": false, "cmd": "/usr/bin/docker pull 192.168.186.159:5000/cluster-proportional-autoscaler-amd64:1.3.0", "msg": "[Errno 2] No such file or directory", "rc": 2}
在三个节点上安装docker，并配置可访问私库
$ sudo yum install yum-utils device-mapper-persistent-data lvm2
$ sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
$ sudo yum update
$ sudo yum install docker-ce-18.06.2.ce
$ sudo mkdir /etc/docker
$ sudo gedit /etc/docker/daemon.json
#########################start
{ "insecure-registries":["192.168.186.159:5000"] }
#########################end
$ sudo mkdir -p /etc/systemd/system/docker.service.d
$ sudo systemctl daemon-reload
$ 
再试
$ ansible-playbook -i inventory/testcluster/hosts.ini cluster.yml -t download -b -v -k
FAILED! => {"attempts": 4, "changed": false, "dest": "/tmp/releases/kubeadm", "msg": "Request failed: <urlopen error [Errno 101] Network is unreachable>", "state": "absent", "url": "https://storage.googleapis.com/kubernetes-release/release/v1.13.3/bin/linux/amd64/kubeadm"}
类似的还有下载https://storage.googleapis.com/kubernetes-release/release/v1.13.3/bin/linux/amd64/hyperkube的时候很慢
搭建ftp服务器
修改roles/download/defaults/main.yml文件的kubeadm_download_url字段，下载地址指向ftp服务器
再试
$ ansible-playbook -i inventory/testcluster/hosts.ini cluster.yml -t download -b -v -k
{"attempts": 4, "changed": true, "cmd": ["/usr/bin/docker", "pull", "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.10.1"], "delta": "0:00:15.105840", "end": "2019-03-06 20:50:49.669624", "msg": "non-zero return code", "rc": 1, "start": "2019-03-06 20:50:34.563784", "stderr": "Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", "stderr_lines": ["Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"], "stdout": "", "stdout_lines": []}
通过自建私库解决
修改inventory/testcluster/group_vars/k8s-cluster/k8s-cluster.yml，修改kube_image_repo字段到私库
再试
$ ansible-playbook -i inventory/testcluster/hosts.ini cluster.yml -t download -b -v -k
FAILED! => {"changed": false, "checksum": "dbec55ebf7be40cb483ff80897383bfdea0b1e73", "msg": "Destination directory /etc/kubernetes does not exist"}
安装kubeadm（所有节点）
$ sudo gedit /etc/yum.repos.d/kubernetes.repo ####上阿里云源 
$ sudo setenforce 0
$ sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
$ sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
再试
$ ansible-playbook -i inventory/testcluster/hosts.ini cluster.yml -t download -b -v -k
{"changed": true, "cmd": ["/usr/local/bin/kubeadm", "config", "images", "pull", "--config=/etc/kubernetes/kubeadm-images.yaml"], "delta": "0:00:15.167607", "end": "2019-03-06 21:27:32.619660", "msg": "non-zero return code", "rc": 1, "start": "2019-03-06 21:27:17.452053", "stderr": "failed to pull image \"gcr.io/google_containers/kube-apiserver:v1.13.3\": output: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\n, error: exit status 1", "stderr_lines": ["failed to pull image \"gcr.io/google_containers/kube-apiserver:v1.13.3\": output: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", ", error: exit status 1"], "stdout": "", "stdout_lines": []}
修改inventory/testcluster/group_vars/k8s-cluster/k8s-cluster.yml的kube_image_repo字段到私库
再试
$ ansible-playbook -i inventory/testcluster/hosts.ini cluster.yml -t download -b -v -k
启动集群
$ ansible all -i inventory/testcluster/hosts.ini -m command -a 'swapoff -a' -u root -k #所有节点关闭交换分区
$ ansible-playbook -i inventory/testcluster/hosts.ini cluster.yml -b -v -k
FAILED - RETRYING: Configure | Check if etcd cluster is healthy
关闭防火墙（所有节点），也可以打开相关端口https://github.com/kubernetes-sigs/kubespray/issues/2767#issuecomment-404402514
$ ansible all -i inventory/testcluster/hosts.ini -m command -a 'swapoff -a' -u root -k #所有节点关闭交换分区
$ ansible-playbook -i inventory/testcluster/hosts.ini cluster.yml -b -vvv -k
TASK [kubernetes-apps/cluster_roles : Kubernetes Apps | Wait for kube-apiserver]



====================================================
查看端口是否运行
sudo lsof -i:6443
重置
$ ansible-playbook -i inventory/testcluster/hosts.ini --become --become-user=root reset.yml
运行新命令
https://github.com/kubernetes-sigs/kubespray/blob/master/docs/getting-started.md
https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ansible.md
$ ansible-playbook -i inventory/testcluster/hosts.ini  --become --become-user=root cluster.yml -b -vvv


